# Generated by Django 2.2.7 on 2020-02-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bot',
            new_name='Bot_Table',
        ),
    ]
