# Generated by Django 2.2.7 on 2020-02-17 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='id',
            new_name='idd',
        ),
    ]
