# Generated by Django 2.2.7 on 2020-02-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_auto_20191213_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('token', models.CharField(max_length=70, null=True)),
                ('admin_id', models.IntegerField(null=True)),
                ('max_team_size', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='node',
            options={},
        ),
        migrations.AddField(
            model_name='node',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
