# Generated by Django 2.2.7 on 2020-02-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_auto_20200217_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='situation',
            field=models.CharField(max_length=50, null=True),
        )
    ]
