# Generated by Django 2.2.7 on 2020-02-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_auto_20200217_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='idd',
            new_name='uid',
        ),
    ]
