# Generated by Django 2.2.7 on 2020-02-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0003_auto_20200216_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
