# Generated by Django 2.2.7 on 2020-02-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0003_auto_20200222_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captain',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
