# Generated by Django 2.2.7 on 2020-02-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0004_auto_20200224_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunter',
            name='tframe',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='uni',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
