# Generated by Django 2.2.7 on 2020-02-24 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0005_auto_20200224_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bot.Captain'),
        ),
    ]
