# Generated by Django 2.2.7 on 2021-11-12 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0006_auto_20200224_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot_table',
            name='admin_id',
        ),
        migrations.CreateModel(
            name='AdminId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.IntegerField(null=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bot.Bot_Table')),
            ],
        ),
    ]
